In [ ]:
import pandas as pd 

df =pd.read_csv("orders.csv")

In [ ]:
# print(df)

df["values"]=[i for i in range (len(df)) ]

print(df)

some common functions

In [55]:

# df.tail()
# df.head()

#df.columns
# df.describe
# df.index
# df.info
# len(df)
# df.info
# df.loc[0]
# df.iloc[0]

# df.shape
# df.axes
# df.ndim
df.dtypes

OrderID          int64
CustomerName    object
Product         object
Category        object
Quantity         int64
Price            int32
OrderDate       object
Shipped         object
Country         object
values           int64
dtype: object

selection by column

In [ ]:
# print(df.to_string())

print(df["CustomerName"])
print(df["CustomerName"])

selection by rows

In [ ]:
print(df.loc[35])
print(df.loc[35 ,["values"]])

values search

In [ ]:
values=int(input("enter a value"))

try:
    print(df.loc[values])

except Exception as e:
    print(e)

Filtering

In [ ]:
# print(df.to_string)

big_value=df[df["values"]>=30]

print(big_value)

In [ ]:
high=df[df["Quantity"] >=2]

print(high)

In [ ]:
diff=df[(df["Country"]=="UAE") | (df["Shipped"]=="No")]

print(diff )

sim=df[(df["Country"]=="UAE") & (df["Shipped"]=="No")]
print(sim)

Aggrigation function

In [ ]:
print(df.mean(numeric_only=True))

print(df.sum(numeric_only=True))
print(df.min(numeric_only=True))
print(df.max(numeric_only=True))
print(df.count())

In [ ]:
print(df["values"].mean())
print(df["values"].sum())
print(df["values"].min())
print(df["values"].max())
print(df["values"].count())

GROUPBY Function

In [ ]:
group=df.groupby("Country")
print(group["values"].mean())
print(group["values"].sum())
print(group["values"].min())
print(group["values"].max())

DATA Cleaning

In [38]:
# df=df.drop(columns="values")

print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country  values
0   1200.0  2024-06-01     Yes           USA       0
1    150.0  2024-06-03      No        Canada       1
2    300.0  2024-06-04     Yes           UAE       2
3     45.0  2024-06-05     Yes     Singapore       3
4     80.0  2024-06-06      No        Mexico       4
5      5.0  2024-06-07     Yes           UAE       5
6    450.0  2024-06-08     Yes            UK       6
7    220.0  2024-06-09      No   South Korea       7
8      1.5  2024-06-10     Yes         Italy       8
9     35.0  2024-06-11     Yes         Japan       9
10    85.0  2024-06-12     Yes        France      10
11   180.0  2024-06-13      No         India      11
12    12.0  2024-06-14     Yes     Australia      12
13    25.0  2024-06-15     Yes         Spain      13
14   280.0  2024-06-16      No         China      14
15     8.0  2024-06-17     Yes         Egypt      15
16    45.0  2024-06-18     Yes        Poland      16
17    65.0  2024-06-19      No           USA      17
18    15.0  2024-06-20     Yes         Japan      18
19   120.0  2024-06-21     Yes  Saudi Arabia      19
20     3.5  2024-06-22      No        Canada      20
21    95.0  2024-06-23     Yes        Brazil      21
22    35.0  2024-06-24     Yes       Germany      22
23     4.0  2024-06-25      No      Pakistan      23
24    28.0  2024-06-26     Yes        Sweden      24
25    75.0  2024-06-27     Yes        France      25
26    22.0  2024-06-28      No     Argentina      26
27     2.5  2024-06-29     Yes        Russia      27
28   110.0  2024-06-30     Yes   South Korea      28
29    18.0  2024-07-01      No         Italy      29
30    32.0  2024-07-02     Yes       Morocco      30
31   140.0  2024-07-03     Yes       Germany      31
32    42.0  2024-07-04      No      Colombia      32
33     0.8  2024-07-05     Yes           USA      33
34    55.0  2024-07-06     Yes         Japan      34
35    68.0  2024-07-07      No            UK      35
36   125.0  2024-07-08     Yes      Portugal      36
37    28.0  2024-07-09     Yes           NaN      37
38    18.0  2024-07-10      No   South Korea      38
39    35.0  2024-07-11     Yes           NaN      39

In [40]:
df=df.dropna(subset="values")

df =df.fillna({"Country":"none"})
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country  values
0   1200.0  2024-06-01     Yes           USA       0
1    150.0  2024-06-03      No        Canada       1
2    300.0  2024-06-04     Yes           UAE       2
3     45.0  2024-06-05     Yes     Singapore       3
4     80.0  2024-06-06      No        Mexico       4
5      5.0  2024-06-07     Yes           UAE       5
6    450.0  2024-06-08     Yes            UK       6
7    220.0  2024-06-09      No   South Korea       7
8      1.5  2024-06-10     Yes         Italy       8
9     35.0  2024-06-11     Yes         Japan       9
10    85.0  2024-06-12     Yes        France      10
11   180.0  2024-06-13      No         India      11
12    12.0  2024-06-14     Yes     Australia      12
13    25.0  2024-06-15     Yes         Spain      13
14   280.0  2024-06-16      No         China      14
15     8.0  2024-06-17     Yes         Egypt      15
16    45.0  2024-06-18     Yes        Poland      16
17    65.0  2024-06-19      No           USA      17
18    15.0  2024-06-20     Yes         Japan      18
19   120.0  2024-06-21     Yes  Saudi Arabia      19
20     3.5  2024-06-22      No        Canada      20
21    95.0  2024-06-23     Yes        Brazil      21
22    35.0  2024-06-24     Yes       Germany      22
23     4.0  2024-06-25      No      Pakistan      23
24    28.0  2024-06-26     Yes        Sweden      24
25    75.0  2024-06-27     Yes        France      25
26    22.0  2024-06-28      No     Argentina      26
27     2.5  2024-06-29     Yes        Russia      27
28   110.0  2024-06-30     Yes   South Korea      28
29    18.0  2024-07-01      No         Italy      29
30    32.0  2024-07-02     Yes       Morocco      30
31   140.0  2024-07-03     Yes       Germany      31
32    42.0  2024-07-04      No      Colombia      32
33     0.8  2024-07-05     Yes           USA      33
34    55.0  2024-07-06     Yes         Japan      34
35    68.0  2024-07-07      No            UK      35
36   125.0  2024-07-08     Yes      Portugal      36
37    28.0  2024-07-09     Yes          nane      37
38    18.0  2024-07-10      No   South Korea      38
39    35.0  2024-07-11     Yes          nane      39

In [ ]:
# df["Country"]=df["Country".replace({"India":"INDIA"})]

# print(df["Country"])

TypeError: replace expected at least 2 arguments, got 1

In [47]:
# df["Category"]=df["Category"].str.lower

print(df)

    OrderID      CustomerName                Product  \
0      1001        John Smith                 Laptop
1      1002         Sarah Lee             Headphones
2      1003          Ali Khan           Office Chair
3      1004        Alice Wong              Desk Lamp
4      1005     Carlos Mendez               Keyboard
5      1006      Nora Ibrahim               Notebook
6      1007       Emily Davis          Standing Desk
7      1008        James Park                Monitor
8      1009       Maria Rossi                    Pen
9      1010  Takeshi Nakamura                  Mouse
10     1011     Sophie Martin                 Webcam
11     1012         Raj Patel           File Cabinet
12     1013       Emma Wilson                Stapler
13     1014   Diego Rodriguez              USB Drive
14     1015         Lisa Chen              Bookshelf
15     1016      Ahmed Hassan          Printer Paper
16     1017     Anna Kowalski         Wireless Mouse
17     1018     Michael Brown         Desk Organizer
18     1019       Yuki Tanaka             Calculator
19     1020   Fatima Al-Zahra             Whiteboard
20     1021    David Thompson           Highlighters
21     1022    Isabella Silva      Bluetooth Speaker
22     1023    Oliver Schmidt           Office Plant
23     1024        Zara Ahmed           Sticky Notes
24     1025    Lucas Anderson           Tablet Stand
25     1026      Chloe Dubois         Paper Shredder
26     1027     Miguel Torres         Desk Chair Mat
27     1028       Nina Petrov           Binder Clips
28     1029      Seo-yeon Kim      Wireless Keyboard
29     1030   Giuseppe Romano          Desk Calendar
30     1031      Amira Hassan                USB Hub
31     1032     Thomas Müller       Document Scanner
32     1033   Sofia Rodriguez  Desk Drawer Organizer
33     1034      Alex Johnson            Index Cards
34     1035     Yuki Yamamoto          Monitor Stand
35     1036     Emma Thompson     Desk Lamp with USB
36     1037     Carlos Santos       Wireless Earbuds
37     1038    Leila Mansouri               Desk Pad
38     1039        Daniel Kim            Power Strip
39     1040      Anna Ivanova             Desk Clock

                                             Category  Quantity   Price  \
0   <bound method StringMethods.lower of <pandas.c...         1  1200.0
1   <bound method StringMethods.lower of <pandas.c...         2   150.0
2   <bound method StringMethods.lower of <pandas.c...         1   300.0
3   <bound method StringMethods.lower of <pandas.c...         3    45.0
4   <bound method StringMethods.lower of <pandas.c...         2    80.0
5   <bound method StringMethods.lower of <pandas.c...         5     5.0
6   <bound method StringMethods.lower of <pandas.c...         1   450.0
7   <bound method StringMethods.lower of <pandas.c...         2   220.0
8   <bound method StringMethods.lower of <pandas.c...        10     1.5
9   <bound method StringMethods.lower of <pandas.c...         1    35.0
10  <bound method StringMethods.lower of <pandas.c...         1    85.0
11  <bound method StringMethods.lower of <pandas.c...         2   180.0
12  <bound method StringMethods.lower of <pandas.c...         3    12.0
13  <bound method StringMethods.lower of <pandas.c...         5    25.0
14  <bound method StringMethods.lower of <pandas.c...         1   280.0
15  <bound method StringMethods.lower of <pandas.c...        20     8.0
16  <bound method StringMethods.lower of <pandas.c...         2    45.0
17  <bound method StringMethods.lower of <pandas.c...         1    65.0
18  <bound method StringMethods.lower of <pandas.c...         1    15.0
19  <bound method StringMethods.lower of <pandas.c...         1   120.0
20  <bound method StringMethods.lower of <pandas.c...         8     3.5
21  <bound method StringMethods.lower of <pandas.c...         1    95.0
22  <bound method StringMethods.lower of <pandas.c...         2    35.0
23  <bound method StringMethods.lower of <pandas.c...        15     4.0
24  <bound method StringMethods.lower of <pandas.c...         1    28.0
25  <bound method StringMethods.lower of <pandas.c...         1    75.0
26  <bound method StringMethods.lower of <pandas.c...         1    22.0
27  <bound method StringMethods.lower of <pandas.c...        12     2.5
28  <bound method StringMethods.lower of <pandas.c...         1   110.0
29  <bound method StringMethods.lower of <pandas.c...         1    18.0
30  <bound method StringMethods.lower of <pandas.c...         1    32.0
31  <bound method StringMethods.lower of <pandas.c...         1   140.0
32  <bound method StringMethods.lower of <pandas.c...         1    42.0
33  <bound method StringMethods.lower of <pandas.c...       100     0.8
34  <bound method StringMethods.lower of <pandas.c...         1    55.0
35  <bound method StringMethods.lower of <pandas.c...         1    68.0
36  <bound method StringMethods.lower of <pandas.c...         1   125.0
37  <bound method StringMethods.lower of <pandas.c...         1    28.0
38  <bound method StringMethods.lower of <pandas.c...         2    18.0
39  <bound method StringMethods.lower of <pandas.c...         1    35.0

     OrderDate Shipped       Country  values
0   2024-06-01     Yes           USA       0
1   2024-06-03      No        Canada       1
2   2024-06-04     Yes           UAE       2
3   2024-06-05     Yes     Singapore       3
4   2024-06-06      No        Mexico       4
5   2024-06-07     Yes           UAE       5
6   2024-06-08     Yes            UK       6
7   2024-06-09      No   South Korea       7
8   2024-06-10     Yes         Italy       8
9   2024-06-11     Yes         Japan       9
10  2024-06-12     Yes        France      10
11  2024-06-13      No         India      11
12  2024-06-14     Yes     Australia      12
13  2024-06-15     Yes         Spain      13
14  2024-06-16      No         China      14
15  2024-06-17     Yes         Egypt      15
16  2024-06-18     Yes        Poland      16
17  2024-06-19      No           USA      17
18  2024-06-20     Yes         Japan      18
19  2024-06-21     Yes  Saudi Arabia      19
20  2024-06-22      No        Canada      20
21  2024-06-23     Yes        Brazil      21
22  2024-06-24     Yes       Germany      22
23  2024-06-25      No      Pakistan      23
24  2024-06-26     Yes        Sweden      24
25  2024-06-27     Yes        France      25
26  2024-06-28      No     Argentina      26
27  2024-06-29     Yes        Russia      27
28  2024-06-30     Yes   South Korea      28
29  2024-07-01      No         Italy      29
30  2024-07-02     Yes       Morocco      30
31  2024-07-03     Yes       Germany      31
32  2024-07-04      No      Colombia      32
33  2024-07-05     Yes           USA      33
34  2024-07-06     Yes         Japan      34
35  2024-07-07      No            UK      35
36  2024-07-08     Yes      Portugal      36
37  2024-07-09     Yes          nane      37
38  2024-07-10      No   South Korea      38
39  2024-07-11     Yes          nane      39

In [49]:
print(df.columns)

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country', 'values'],
      dtype='object')

In [50]:
df["Price"]=df["Price"].astype(int)

print(df["Price"])

0     1200
1      150
2      300
3       45
4       80
5        5
6      450
7      220
8        1
9       35
10      85
11     180
12      12
13      25
14     280
15       8
16      45
17      65
18      15
19     120
20       3
21      95
22      35
23       4
24      28
25      75
26      22
27       2
28     110
29      18
30      32
31     140
32      42
33       0
34      55
35      68
36     125
37      28
38      18
39      35
Name: Price, dtype: int32

In [ ]:
# df=df.drop_duplicates()

# del df("country")

# df.pop("country")

ADD Functions

In [ ]:
def add__(i,j):
    return i+j

df["Quantity"]=df["Quantity"].pipe(add__,10)


df

APPLY functiom ( LAMBDA AND MAP FUNCTION)

In [ ]:
df["Quantity"].apply(lambda x: x+2)

# df.applymap(lambda x:x*2)

df[["Quantity"]]=df[["Quantity"]].applymap(lambda x:x*2)

In [2]:
import pandas as pd
df2=pd.read_csv("orders.csv")

df2

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN

COPY FUNCTION

In [13]:
de=df2.copy()

de=de.drop([i for i in range(0,35)], axis=0)

de

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN

REINDEX

In [17]:
de=de.reindex([36,35,39,37,38])
de

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

RENAMING COLUMN

In [19]:
de.rename(columns={"Country":"COUNTRY","Price":"PRICE"})

,OrderID,CustomerName,Product,Category,Quantity,PRICE,OrderDate,Shipped,COUNTRY
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

SORTING

In [25]:
de.sort_values(by="Price")

de.sort_values(by="Price" ,ascending=False)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

GROUPBY FUNCTION

In [32]:
de.groupby("Category")

groups=de.groupby("Category").groups

groups2=de.groupby("Category").filter(lambda x:len(x)==2)

groups2

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [36]:
group=de.groupby("Category")

print(group['Price'].mean())
print('-'*20)
print(group['Price'].min())
print(group['Price'].max())
print(group['Price'].sum())

Category
Electronics    71.500000
Furniture      43.666667
Name: Price, dtype: float64
--------------------
Category
Electronics    18.0
Furniture      28.0
Name: Price, dtype: float64
Category
Electronics    125.0
Furniture       68.0
Name: Price, dtype: float64
Category
Electronics    143.0
Furniture      131.0
Name: Price, dtype: float64

VALUE ,UNIQUE ,NUNIQUE

In [38]:
de["Category"].sort_values()
de["Category"].unique()
de["Category"].nunique()

2

SAMPLE FUNCTION

In [39]:
de.sample(2)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,NaN
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal

PANDAS PROFILE REPORT

In [5]:
from ydata_profiling import ProfileReport

import pandas as pd

df = pd.read_csv("orders.csv")
profile = ProfileReport(df)
profile.to_file("report.html")

C:\Users\ADINATH\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Matplotlib is building the font cache; this may take a moment.
100%|██████████| 9/9 [00:00<00:00, 33.10it/s]00<00:00, 22.59it/s, Describe variable: Country]
Summarize dataset: 100%|██████████| 27/27 [00:02<00:00, 10.63it/s, Completed]
Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

TypeError: asarray() got an unexpected keyword argument 'copy'